.TH SSS 1 sss
.SH NAME
sss \- simple screenshot program
.SH SYNOPSIS

$ sss [\fIOPTION\fR] output.png

.SH DESCRIPTION
This program is a 2 button screenshot program. By default
if the user gives no options it will take a screen shot
of a user drawn area and write it to screenshot.png.
.P
The user can draw a rectangular area by holding left mouse
button and dragging. A screenshot is only taken when
the user presses right mouse button. This means you can
draw as many rectangles as you like until you want to take a
screenshot.
.P
The default directory where screenshots are stored is in
the \fI$HOME\fR environment variable

.SH OPTIONS
.B \-f
?<\fIfilename\fR>

takes a screenshot of entire screen, accepts optional
argument of a filename e.g:
.P
    ----------------

    $ sss -f out.png

    ----------------

if no argument is given output is written to fullscreen.png

.B \-n
?<\fIfilename\fR>

takes a screenshot of user drawn area, accepts optional
argument of a filename e.g:
.P
    ----------------

    $ sss -n out.png

    ----------------

if no argument is given output is written to screenshot.png, this
is the same behaviour is if no options were given

.SH CONFIGURATION

Default directory is \fI$HOME\fR environment variable.
To change the directory for screenshots to be copied to, assign a value"
to \fI$SS_DIR\fR env variable e.g.: 

    ----------------

    $ export SS_DIR=/home/username/screenshots

    ----------------

The above command can be put in your .zshrc, .bashrc, etc - depending on the
shell you are using( consult its documentation on exporting environment variables)

Apart from that there should be a supplied \fBconfig.h\fR file in the cloned
repository. Configuration is done by editing this file.
The following are defined in that file.

.B • LINE_WIDTH
- defines the width of the border around the user
drawn area, screenshots are bound inside this border

.B • LINE_COLOR
- 24bit hex-color code defines the color of the border
note: the color code used is dependent on your root displays
color depth

.B • CURSOR
- "string" defines the xcursor to be used, refer
to your cursor theme for options
